#Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
- jekyll-feed
- jekyll-toc
- jekyll-seo-tag
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache
title: DeathHacks
description: DeathHacks
minimal_mistakes_skin: "dark"
include: ["_pages"]
google: #searchengineID
  search_engine_id: f126427cddacb400f

author:
  name: "DeathHack"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Nik/Deathvoice <br>
  Vulnerability Analyst / Offensive Security / Intel Goblin<br>  
  Founder of Error418 Cyber Security" # Note: Markdown is allowed
  location: "Aus"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DeathxVoices"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DeathHacks"
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/nik-george-9b3423135/"

defaults:
  # _pages
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      nav: main
      layout: single
      author_profile: true


