#Build settings
markdown: GFM
remote_theme: jekyll/minima
plugins:
- jekyll-feed
- jekyll-toc
- jekyll-seo-tag
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Deathtricks
description: A collection of collated resources
minima:
  skin: dark
